default:
  data_preparation:
    # The name of the cohort
    cohort_name: "newborns_b_perinatal"
    perinatal_name: "scratch/newborns_b_perinatal/newborns_b_perinatal_cohort.rds"
    
    # Child birth date filters the cohort by age
    child_birth_date_min: "01/01/2015"
    child_birth_date_max: "31/12/2024"

    # The cohort is allowed to be unregistered for this many days 
    # in this period
    child_live_slack_days: 31

   # Postal code link to homes will  be considered on this target date
    postcode_target_date: "31/12/2025"
    # Neighbourhood geo link to homes will be considered on this target date
    gwb_target_date: "31/12/2025"
    # Corop geo link to homes will be considered on this target date
    corop_target_date: "31/12/2025"
    
    # Income will be deflated to cpi_base_year euros.
    cpi_base_year: 2024
    
    # Mother's household income: year before birth and year of birth,
    # so this range runs from (first birth year - 1) to (last birth year)
    parent_income_year_min: 2014
    parent_income_year_max: 2024
    
    # Parent wealth year range
    parent_wealth_year_min: 2015
    parent_wealth_year_max: 2024
    
    # remove gestational age at given days
    cut_off_days_min: 168
    cut_off_days_max: 294
    
    # when we measure the household composition of the child
    childhood_home_age: 0

    # health outcomes range, year of birth and year child turns 1
    health_year_min: 2015
    health_year_max: 2024 #set to 2025 once ZWVZORGKOSTENTAB2025 is out
    
  file_locations:
    # The data folder is the root folder of the cbs microdata tables
    data_folder: "G:/"
    # The scratch folder is used to write intermediate output
    scratch_folder: "scratch/newborns_b_perinatal"
    
   # path to the cbs microdata
    gba_data: "Bevolking/GBAPERSOONTAB/2024/GBAPERSOON2024TABV3.sav"
    gbaao_data: "Bevolking/GBAADRESOBJECTBUS/GBAADRESOBJECT2024BUSV1.sav"
    kind_data: "Bevolking/KINDOUDERTAB/KINDOUDER2025TABV2.sav"
    postcode_data: "BouwenWonen/VSLPOSTCODEBUS/VSLPOSTCODEBUSV2026031.sav"
    vslgwb_data: "BouwenWonen/VSLGWBTAB/VSLGWB2025TAB03V1.sav"
    household_data: "Bevolking/GBAHUISHOUDENSBUS/GBAHUISHOUDENS2024BUSV1.sav"

    # perined data
    perined_data: 'resources/8151_PERINED.rds'
    
    # resources
    cpi_index_data: "resources/Consumentenprijzen__prijsindex_2015_100_14112022_221558.xlsx"
    migration_data: "K:/Utilities/Code_Listings/SSBreferentiebestanden/LANDAKTUEELREFV15.SAV"
    corop_data: "K:/Utilities/HULPbestanden/GebiedeninNederland/GIN"
    birthweight_data: "resources/Hoftiezer_Geboortegewicht curves.xlsx"
    boys_sheet: "Tabel jongens"
    girls_sheet: "Tabel meisjes"
    opleiding_data: "K:/Utilities/Code_Listings/SSBreferentiebestanden/OPLEIDINGSNRREFV36.SAV"
    cto_data: "K:/Utilities/Code_Listings/SSBreferentiebestanden/CTOREFV13.SAV"
  
